### ISSUE TITLE
Cache active campaigns in Redis.

### ISSUE THREAD

**Issue by rapala61** [DoSomething/gambit-campaigns#1003]
_OVERVIEW_
-------------------
#### User Story
When the Conversations API sends a GET request to the `/campaigns` route, the response should be cached in Redis, so that any subsequent request gets a cached response until it expires or is removed manually from the Redis cache.

#### Why This Matters
Caching makes our infrastructure more efficient and resilient to momentary platform failures (in theory).

#### Related Issues

Convo [issue#217](https://github.com/DoSomething/gambit-conversations/issues/217)

**Comment by rapala61** [comment]
Elevating this issue to high priority. We just had a pretty severe outage in our Rogue platform that also took down Phoenix. If we had these campaigns cached in Redis, we could have been operational to non reportback/signup texts. Unfortunately, all incoming user texts are failing at this moment. [Slack thread](https://dosomething.slack.com/archives/C0YGXUE01/p1515606077000535)

cc @aaronschachter @justkika

**Comment by aaronschachter** [comment]
Refs https://github.com/orgs/DoSomething/teams/team-odoyle/discussions/2

**Comment by aaronschachter** [comment]
Closed in #1019
